apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        -name: node-app
         image: gcr.io/gcp-training-377619/node-app:v2
         args: ["--PORT","=","5000"]
          
         
        